name: Deploy package
on:
  push:
    branches:
      - main
jobs:
  package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'srclaunch'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          # always-auth: true
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@srclaunch'
      - run: yarn install
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
